# Generated by Django 3.0 on 2021-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
