# Generated by Django 3.2.7 on 2021-09-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
    ]
