# Generated by Django 3.2.7 on 2021-09-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
