# Generated by Django 3.2.7 on 2021-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
