# Generated by Django 3.2.7 on 2021-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
